---

production:
  hosts:
    appservers:
      app1:
        ansible_user: ubuntu
#      app2:
#        ansible_user: ubuntu
#      app3:
#        ansible_user: ubuntu

control:
  hosts:
    jenkins:
      master:
        control1:
          ansible_user: ubuntu
      agent:
        control2:
          ansible_user: ubuntu