global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true