pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git(url: 'https://github.com/devopsjourney1/terraform-testing', branch: 'master')
                sh 'docker build -t mywebapp:${BUILD_NUMBER} docker/docker_app1/.'
            }
        }
        stage('Build Docker image') {
            agent {
                docker {
                    image 'mywebapp:${BUILD_NUMBER}'
                }    
            }
            steps {
                sh 'python --version'
                sh 'pip --version'
            }
        }
        stage('Test App') {             
            steps {
                sh 'curl localhost'
            }
        }
    }
}