apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mywebapp
    env: prod
spec:
  containers:
  - name: mycontainer
    image: devopsjourney1/mywebapp:prod
    imagePullPolicy: Always   
    resources:
      requests:
        memory: "16Mi" # mebibytes
        cpu: "500m"    # 500milliCPUs (1/2 CPU)
      limits:
        memory: "16Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000