---
- name: Install Jenkins Prerequirements
  hosts: control
  become: true
  tasks:
  - name: Install openjdk and ca-certificates (pre-req for jenkins)
    apt: 
      name: 
      - openjdk-11-jre
      - ca-certificates
      state: latest
      update_cache: yes
    tags: 
    - always

- name: Install Jenkins Master Tasks
  hosts: master
  become: true
  tasks:
  - name: Add apt-key
    shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    tags: 
    - master

  - name: Add a Jenkins apt repository entry
    shell: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    tags: 
    - master


  - name: Install Jenkins
    apt: 
      name: jenkins
      state: latest
      update_cache: yes
    tags: 
    - master
  
  - name: Waits for Jenkins service to start and returns Admin password
    shell: sleep 30 && cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkinsPassword
    tags: 
    - master

  - debug: msg="Jenkins Admin Password is {{ jenkinsPassword.stdout }}"
    tags: 
    - master

- name: Install Jenkins Agent Tasks
  hosts: agents
  become: true
  tasks:

  - name: Ensure group "jenkins" exists
    ansible.builtin.group:
      name: jenkins
      state: present
    tags: 
    - agents

  - name: Ensure user "jenkins" exists and has the correct groups
    ansible.builtin.user:
      name: jenkins
      groups: 
      - docker
      - jenkins
      append: yes
    tags: 
    - agents