pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git(url: 'https://github.com/devopsjourney1/terraform-testing', branch: 'master')
            }
        }
        stage('Build') {
            steps {
                sh 'ls -ltr'
            }
        }
    }
}